// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAScqC1n7pdPkbJT-npNPl68faQrAjzOwo',
    appId: '1:233176771191:web:1ea8ddb12c6c869c687472',
    messagingSenderId: '233176771191',
    projectId: 'news-aggregator-app-97965',
    authDomain: 'news-aggregator-app-97965.firebaseapp.com',
    storageBucket: 'news-aggregator-app-97965.firebasestorage.app',
    measurementId: 'G-D6BY5CS2R2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-nifsl_dQVhAIdv3VEVC8m0mEqtwd_KA',
    appId: '1:233176771191:android:ee91e8177f1e73ed687472',
    messagingSenderId: '233176771191',
    projectId: 'news-aggregator-app-97965',
    storageBucket: 'news-aggregator-app-97965.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-0oYwTC5EFHQ4i5BEa1eJJak5CZ5do-M',
    appId: '1:233176771191:ios:eb799247c53e97cb687472',
    messagingSenderId: '233176771191',
    projectId: 'news-aggregator-app-97965',
    storageBucket: 'news-aggregator-app-97965.firebasestorage.app',
    iosBundleId: 'com.example.newsAggregatorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-0oYwTC5EFHQ4i5BEa1eJJak5CZ5do-M',
    appId: '1:233176771191:ios:eb799247c53e97cb687472',
    messagingSenderId: '233176771191',
    projectId: 'news-aggregator-app-97965',
    storageBucket: 'news-aggregator-app-97965.firebasestorage.app',
    iosBundleId: 'com.example.newsAggregatorApp',
  );
}
